export const BOUNDS:[[number,number],[number,number]]=[[25,-12],[180,80]];
export const START:[[number,number],[number,number]]=[[42,-6],[150,58]];
export interface ModelInfo{id:string;name:string;org:string;res:string;license:string}
export const MODELS:ModelInfo[]=[
{id:'gfs_seamless',name:'GFS',org:'NOAA / NCEP',res:'0.25 deg, about 28 km',license:'US Government work, public domain'},
{id:'ecmwf_ifs025',name:'ECMWF IFS',org:'ECMWF open data',res:'0.25 deg, about 28 km',license:'CC BY 4.0'},
{id:'icon_seamless',name:'ICON',org:'DWD',res:'global 0.125 deg, about 13 km over Asia',license:'CC BY 4.0'}
];
export const STYLES:Record<string,string>={light:'https://tiles.openfreemap.org/styles/positron',standard:'https://tiles.openfreemap.org/styles/bright'};
export const RAMP:[number,string][]=[[0,'#4b2a7b'],[5,'#375a8c'],[10,'#1f8a8a'],[15,'#2fa05a'],[20,'#a3a01a'],[25,'#c25a12']];
export interface SourceInfo{key:string;name:string;what:string;license:string;attribution:string;coverage:string;update:string}
export const SOURCES:SourceInfo[]=[
{key:'grid',name:'Open-Meteo Forecast API (wind grid)',what:'10 m wind speed and direction sampled every 6 degrees from the selected model, 48 hourly steps',license:'Data CC BY 4.0; free API for non-commercial use',attribution:'Weather data by Open-Meteo.com',coverage:'25E-180E, 12S-78N',update:'Model runs, typically every 6 h; cached 3 h at the edge'},
{key:'point',name:'Open-Meteo Forecast API (location forecast)',what:'Hourly single-point forecast for 5 days and sunrise/sunset',license:'Data CC BY 4.0; free API for non-commercial use',attribution:'Weather data by Open-Meteo.com',coverage:'25E-180E, 12S-80N',update:'Model runs, typically every 6 h; cached 10 min at the edge'},
{key:'geocode',name:'Open-Meteo Geocoding API',what:'Place search and autocomplete, filtered to the Asian domain',license:'CC BY 4.0',attribution:'GeoNames via Open-Meteo',coverage:'Global, filtered to Asia',update:'Continuous'},
{key:'basemap',name:'OpenFreeMap vector tiles',what:'Base map, borders and labels',license:'ODbL data, OpenMapTiles schema',attribution:'OpenFreeMap, OpenMapTiles, data from OpenStreetMap contributors',coverage:'Global',update:'Weekly planet builds'}
];
export const ACK="We acknowledge the use of imagery provided by services from NASA's Global Imagery Browse Services (GIBS), part of NASA's Earth Observing System Data and Information System (EOSDIS).";
SOURCES.push(
{key:'sat',name:'NASA GIBS WMTS capabilities and colormap (via AsiaWX proxy)',what:'Layer list, tile matrix set, tile URL template, available frame times and the published colormap for Himawari-9 layers',license:'Open access through NASA GIBS; check NASA and JMA terms before any commercial use',attribution:ACK,coverage:'Himawari-9 full disk',update:'Capabilities cached 2 min at the edge; colormap cached 1 day'},
{key:'gibs',name:'NASA GIBS Himawari-9 imagery tiles',what:'Colour-rendered Himawari-9 AHI Band 13 infrared, Band 3 red visible and Air Mass RGB, nominally every 10 minutes',license:'Open access through NASA GIBS with the acknowledgment shown here; underlying data from JMA Himawari-9',attribution:ACK,coverage:'Himawari-9 full disk, centred near 140.7E; Asian areas far west or at high latitude are at or beyond the view edge',update:'Nominally 10 minutes; actual latency is not measured by this build'});
SOURCES.push(
{key:'jma',name:'JMA Himawari-9 real-time imagery tiles (via AsiaWX rewrite)',what:'Infrared Band 13, water vapour Band 8 and true colour reproduction, nominally every 10 minutes',license:'Japan Meteorological Agency content, check the JMA terms of use before commercial use',attribution:'Source: Japan Meteorological Agency, Himawari-9',coverage:'Himawari-9 full disk',update:'Nominally 10 minutes; relayed through a Vercel rewrite for browser access'},
{key:'realearth',name:'SSEC RealEarth global composites',what:'Global infrared and visible geostationary composites, hourly',license:'Free with usage limits and attribution; see the RealEarth terms',attribution:'Source: SSEC RealEarth, University of Wisconsin-Madison',coverage:'Global composite, includes western Asia',update:'Hourly'});
SOURCES.push(
{key:'tc',name:'AsiaWX cyclone proxy (/api/tc)',what:'Fetches the JMA, GDACS and Hong Kong Observatory feeds server side, validates and normalises them, and returns one payload with a status line per feed',license:'Depends on the upstream feeds listed below',attribution:'See the individual feeds',coverage:'Asia-Pacific domain',update:'Cached 5 min at the edge; the browser refreshes every 10 min while the layer is on'},
{key:'tc-jma',name:'JMA typhoon information (bosai JSON)',what:'Active system list, analysis and forecast positions to 5 days, 70% probability circles, gale and storm warning areas, pressure and 10-minute mean wind',license:'JMA site terms of use (Public Data License v1.0 basis); attribution required, edits must be stated',attribution:'Source: Japan Meteorological Agency; adapted and redrawn by AsiaWX',coverage:'Western North Pacific and South China Sea systems that JMA tracks',update:'On JMA issuance, normally every 3 or 6 hours'},
{key:'tc-gdacs',name:'GDACS tropical cyclone events',what:'Current cyclone positions, alert level and the agency behind each entry (JTWC or NOAA), used as a cross-check and to list systems JMA does not track',license:'Open; GDACS asks that the source is cited',attribution:'Global Disaster Awareness and Coordination System, GDACS (UN OCHA, European Commission JRC)',coverage:'Global, filtered to the Asia-Pacific domain and to advisories within 12 hours',update:'As agencies issue advisories'},
{key:'tc-hko',name:'Hong Kong Observatory open data, warning summary',what:'Weather warnings and tropical cyclone signals in force for Hong Kong',license:'HKO open data terms through DATA.GOV.HK; check them before commercial use',attribution:'Source: Hong Kong Observatory',coverage:'Hong Kong only',update:'As and when warnings change'});
